### ISSUE TITLE
Support name in TCL for each step

### ISSUE THREAD

**Issue by jcanizalez** [AzBuilder/terrakube-server#114]
Add name field in each step in order to identify it with a user friendly name in UI

```
flow:
  - type: "terraformPlan"
    name: "Plan"
    step: 100
  - type: "terraformApply"
    name: "Apply"
    step: 200
```
